### PR TITLE
TournamentsList updates

### LINKED ISSUE #1143: Littered and confusing /tournaments page
**Describe the bug**
Two UI issues on https://online-go.com/tournaments 

1. Tournaments that have never started are really littering both 'live' and correspondence' pages. For live, majority of "open tournaments" are tourneys that are scheduled to start some day in the past, but never reached minumum participatns - some of them are invite only, and some group memebers only. Its almost as bad for correspondence, both sub-pages have more than the first 25 tournaments these "failed tournaments"

2. Sub-page for sitewide tournament schedule is only named "schedule" 
Its bit confusing for many new users, since both 'live' and correspondence' sub pages alrady have schedules for custom and title tournaments. 

**To Reproduce**
Go to https://online-go.com/tournaments  and see whats there.

**Expected behavior**
1. Do not show old-but-never-started tournaments, no invite-only tournaments, no more groupmembers-only tournaments. At least not by default, and not in any cases at the very first of the list. 

2. Even renaming the 'schedule' to 'sitewide schedule' or something like that would make it more clear. Maybe having it as a landing sub-page on /tournaments, i recon thats the most searched thing there.

**Screenshots**

https://imgur.com/Wn3QyIx
Page 1 nothing but litter.

### PR DESCRIPTION
**Pull request by benjaminpjones**
Fixes #1143 (@kobakitty please verify)

## Proposed Changes
  - Add a toggle that removes stale or exclusive tournaments (default: don't show stale/exclusive).
      - arbitrary filtering was way easier than I thought it would be.  Cool API!
  - Make Schedule the default tab, since it has the official tournaments.
  - Add template args to `PaginatedTable` for tighter types.
  - Add a **models/** dir that can be a home for various types such as types for important API calls. (pretty much just a proof of concept right now)

## Screenshots
Screen Shot 2021-12-19 at 1 59 09 AM
Screen Shot 2021-12-19 at 1 59 41 AM

### CODE REVIEW

File: src/views/TournamentList/TournamentList.tsx [hunk 1]
```diff
@@ -17,23 +17,32 @@
...
 import {PaginatedTable} from "PaginatedTable";
 import * as moment from "moment";
-import {TOURNAMENT_TYPE_NAMES, TOURNAMENT_PAIRING_METHODS, rankRestrictionText, shortRankRestrictionText} from "Tournament";
+import {TOURNAMENT_TYPE_NAMES, shortRankRestrictionText} from "Tournament";
 import tooltip from "tooltip";
+import { Toggle } from "Toggle";
 
 interface TournamentListProperties {
-    filter: any;
+    phase: 'open'|'active'|'finished';
```
Comment (anoek) [inline src/views/TournamentList/TournamentList.tsx:33]: Nice

File: src/lib/preferences.ts [hunk 2]
```diff
@@ -93,7 +93,8 @@ const defaults = {
 
     "supporter.currency": "auto",
     "supporter.interval": "month",
-    "tournaments-tab": "correspondence",
+    "tournaments-tab": "schedule",
```
Comment (anoek) [inline src/lib/preferences.ts:96]: My initial reaction on having this be the default was negative because there's no actionable things on the page allowing players to join anything, but maybe that's not a bad thing as hopefully the next thing someone interested in joining will do is find the live/correspondence sub-tabs, and in doing that they'll learn that there are two tabs there depending on the type of tournament you're interested in joining. So, lets try it :)

Comment (benjaminpjones) [reply src/lib/preferences.ts:96]: That's a valid concern.  As a mentioned in the commit message, this was mostly prompted by a suggestion in the bug.

So anyway if this part needs to be rolled back that's fine by me :)

**Comment by benjaminpjones** [comment]
Thanks for reviewing!
