### PR TITLE
Hide user's empty associations and servers

### LINKED ISSUE #2805: Can't clear other server ranks once I selected one previously
**Describe the bug**
Description above. I selected GoQuest and KGS before in the rank selection and set it back to select a rank, and it displays a ? instead of removing it from the list.

**To Reproduce**
1. Go to Account Linking
2. Select a rank on any association
3. Unselect it and navigate to profile
4. See error - rank displays a ? instead of nothing

**Expected behavior**
Rank displays nothing

**Screenshots**

image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by bodrych**
Fixes #2805

### CODE REVIEW

File: src/views/User/User.tsx [hunk 1]
```diff
@@ -652,46 +652,58 @@ function SelfReportedAccountLinkages({
...
-            <ServerLink name={_("Yike Weiqi")} id={links.yike_username} rank={links.yike_rank} />
-            <ServerLink name={_("GoQuest")} id={links.goquest_username} rank={links.goquest_rank} />
-            <ServerLink
-                name={_("BadukPop")}
-                id={links.badukpop_username}
-                rank={links.badukpop_rank}
-            />
+            {userAssociations.length > 0 && <h3>{_("Associations")}</h3>}
+            {userAssociations.map((props) => (
+                <AssociationLink {...props} />
```
Comment (anoek) [inline src/views/User/User.tsx:700]: Need to have a `key` prop on this to avoid React complaining at us on the console, either the index or name I reckon

File: src/views/User/User.tsx [hunk 2]
```diff
@@ -652,46 +652,58 @@ function SelfReportedAccountLinkages({
...
+            ))}
+
+            {userServers.length > 0 && <h3>{_("Servers")}</h3>}
+            {userServers.map((props) => (
+                <ServerLink {...props} />
```
Comment (anoek) [inline src/views/User/User.tsx:705]: Same here

**Review by anoek — CHANGES_REQUESTED** [review]
Thanks for working on this!

File: src/views/User/User.tsx (hunk 1 above)
Comment (bodrych) [reply src/views/User/User.tsx:700]: I used the spread syntax. The properties are the same as they were (country, id, rank), so react doesn't complain about it.
Should I explicitly define the properties in order to make code more readable maybe?

Comment (GreenAsJade) [reply src/views/User/User.tsx:700]: I think

`{userAssociations.map((props) => (
    <AssociationLink key={props.id} {...props} />
))}`

is needed, which is OK since those associations do have unique ids

**Comment by anoek** [comment]
I see the done message but no new commits - did you forget to push by chance?

**Comment by bodrych** [comment]
Should be okay

**Review by anoek — APPROVED** [review]

**Comment by anoek** [comment]
Thanks!
