### PR TITLE
TimeControlPicker.tsx: sanitize value of numeric inputs

### LINKED ISSUE #1628: Players can create games with null x 10s byo-yomi
**Describe the bug**
When creating a custom challenge a player can leave the number of byo-yomi periods empty and it will create a game with null x () byo-yomi.

For example a game with 2mins + nullx10s byo-yomi will behave like a 2 min absolute time game, but will ignore the warning symbol (I believe) that would normally come with it. It also displays like `2mins + nullx10s`.

**To Reproduce**
1. Play page, create custom challenge
2. Choose Blitz byo-yomi and leave the number of periods blank

**Expected behavior**
This shouldn't be a possible option

E.g.

https://online-go.com/game/40320471

### PR DESCRIPTION
**Pull request by maurelio1234**
Fixes #1628 

## Proposed Changes
 
  - Sanitize values of numeric input fields so that they match the min value if the stored value is falsy.
 
In fact the bug exists on both Canadian and byo-yomi rules. Hopefully the back-end blocks invalid Canadian challenges.

The point here is also starting a discussion on what is the best fix. 
Sanitizing all values in the localstorage before use seems to be a much better fix, but it is a much bigger change and we could also argue that its content is valid since we wrote it... (except when in this precise case).

### CODE REVIEW

**Comment by benjaminpjones** [comment]
>Sanitizing all values in the localstorage before use seems to be a much better fix, but it is a much bigger change and we could also argue that its content is valid since we wrote it... 

Yeah this is a good question. I'm hoping now that `data.get()` and `data.set()` are typed in a way that they have to match, it will be harder to save bad data... but it's still possible especially if the data scheme changes.

**Comment by maurelio1234** [comment]
> @maurelio1234 if you run `npx husky install`, you will be saved from "fix lint" commits grinning

anything against it being in the postinstall so that it is installed automatically? 
https://docs.npmjs.com/cli/v8/using-npm/scripts#pre--post-scripts

**Comment by benjaminpjones** [comment]
No qualms on my end about making installation automatic.  `prepare` seems to be recommended over `postinstall` though.

https://typicode.github.io/husky/#/?id=install
https://github.com/typicode/husky/issues/884

**Comment by maurelio1234** [comment]
> No qualms on my end about making installation automatic.  `prepare` seems to be recommended over `postinstall` though.
> 
> https://typicode.github.io/husky/#/?id=install
> https://github.com/typicode/husky/issues/884

LGTM. 

I just want to avoid having to think about it consciously. 

When I have time I will create another PR with that and see what happens 😏.

**Comment by anoek** [comment]
Thanks for the improvement/fix @maurelio1234 !

File: src/components/TimeControl/TimeControlPicker.tsx [hunk 1]
```diff
@@ -194,7 +194,7 @@ export class TimeControlPicker extends React.PureComponent<
     update_period_time = (ev) => this.syncTimeControl({ period_time: parseInt(ev.target.value) });
     update_periods = (ev) =>
         this.syncTimeControl({
-            periods: Math.max(1, Math.min(300, parseInt(ev.target.value) || 1)),
```
Comment (anoek) [inline src/components/TimeControl/TimeControlPicker.tsx:197]: I hit merge on this too quick, this is still needed as folks can put in whatever they want in those input fields, so folks can create a game with 3248987 periods or whatever. (I should probably validate that on the server too.. but would be good to enforce that here as well)

Comment (maurelio1234) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: I will check again later. But as far as I remember the value comes from the numeric input with a Max and min correctly set. Users cannot change them as they want we just need to make sure we give it a sane initial value. Otherwise it just passes the value forward (like here) without changing it.

**Comment by anoek** [comment]
They're set correctly there but input fields only use that for enforcing it when folks are using the up/down arrows or scroll wheel or whatever. If they type in a number, they can put in whatever they want and it'll accept it, which is the problem and the need for second check.

File: src/components/TimeControl/TimeControlPicker.tsx (hunk 1 above)
Comment (anoek) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: They're set correctly there but input fields only use that for enforcing it when folks are using the up/down arrows or scroll wheel or whatever. If they type in a number, they can put in whatever they want and it'll accept it, which is the problem and the need for second check.

Comment (maurelio1234) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: Oh I see! I will propose something later tonight.

Comment (maurelio1234) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: @anoek what do you think about this approach: https://github.com/online-go/online-go.com/pull/1721 ?

Comment (maurelio1234) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: hmm there's still something missing here... a null value on the storage will still be sent to the backend even though the UI looks sane ...

Comment (shinuito) [reply src/components/TimeControl/TimeControlPicker.tsx:197]: Yes, people can still create null byo-yomi games, presumably if it’s in local storage.
