### PR TITLE
Delay reloading tournament when saving edits

### LINKED ISSUE #2571: "Save tournament" request aborted on success, leaving tournament in edit mode
**Describe the bug**
If you click "Edit Tournament" then "Save Tournament", you're left in edit mode.

**To Reproduce**
1. Create a tournament at https://beta.online-go.com
2. Click "Edit Tournament"
3. Click "Save Tournament"
4. Notice that you are still in "edit" mode.

**Expected behavior**
You're out of edit mode (unless there's some error!), and can see the results of saving the tournament.

**Additional context**
In fact, if you're looking carefully, the tournament leaves edit mode briefly, then goes back into edit mode on a successful save. The problem is that the PUT request **_aborts itself on success_**.

- The "Save" button sends out a `put()` request and exits edit mode.
- The [put request](https://github.com/online-go/online-go.com/blob/devel/src/views/Tournament/Tournament.tsx#L1288) calls `resolve()` on success and `onError()` on failure.
    - ~~Since it's successful, it calls `resolve()`.~~ EDIT: misdiagnosed. The server sends a push notification that aborts the request before sending `"success"`.
- [resolve](https://github.com/online-go/online-go.com/blob/764699c392813ae1deb8c262a1a3853bc75dcaef/src/views/Tournament/Tournament.tsx#L260)'s first move is to abort requests in flight.
    - ~~This aborts the request currently being resolved and calls its `onError()` function.~~ EDIT: misdiagnosed. `resolve()` is never called.
- [onError](https://github.com/online-go/online-go.com/blob/764699c392813ae1deb8c262a1a3853bc75dcaef/src/views/Tournament/Tournament.tsx#L1282) kicks us back into edit mode.

### PR DESCRIPTION
**Pull request by dexonsmith**
If the tournament director clicks "Save Tournament" after making edits, when they're accepted by the server, the server will send a PUSH notification on the tournament channel asking all clients to reload before sending back "success".

Delay this reloading action until we have a response from the "Save" request. Previously, the reload was aborting the about-to-succeed request, kicking the client back into edit mode.

Fixes #2571

### CODE REVIEW

File: src/views/Tournament/Tournament.tsx [hunk 1]
```diff
@@ -129,6 +129,8 @@ interface TournamentInterface {
     opengotha_standings?: boolean;
 }
 
+type EditSaveState = "none" | "saving" | "reload";
```
Comment (dexonsmith) [inline src/views/Tournament/Tournament.tsx:132]: Not sure this is really providing any type safety benefit when using React's useState. Is there some way to declare a type in `useState` that I missed?

Comment (anoek) [reply src/views/Tournament/Tournament.tsx:132]: Yep like this: `React.useState<EditSaveState>("none")`

Comment (anoek) [reply src/views/Tournament/Tournament.tsx:132]: (Once that's in you shouldn't nee dto do any of the "as EditSaveState" stuf fin either the useState call or the setEditSaveState)

Comment (dexonsmith) [reply src/views/Tournament/Tournament.tsx:132]: Yeah, and there are examples of that nearby too... done in 3cb14c68159b83fb4c7c4bf20b5483011e5e54f8.

**Comment by anoek** [comment]
Thanks!
