### PR TITLE
Bug/group links

### LINKED ISSUE #1066: In group chat, clicking a link to another group results in an invalid state
**Describe the bug**
I was having an online group meetup and a member was talking about another group and posted a link to that group. When I clicked the link, some of the cards on the page were for the group he linked to and some of the cards were for the group I came from.

**To Reproduce**
1. Go to the page for any group (`/group/123`)
2. Copy the url for that page
3. Go to the page for another group (`/group/234`)
4. Paste the url you copied into group chat
5. Click the link
6. The page will now be in a weird, invalid state.
7. Now refresh the page.
8. The page should be in a valid state again.
9. Hit the browser back button.
10. The page is in an invalid state again.

**Expected behavior**
The page should cleanly navigate to the page for the group being linked to.

**Screenshots**
Mar-22-2020 10-22-52

**Desktop (please complete the following information):**
 - OS: Mac OSX Catalina
 - Browser: Chrome
 - Version 80

**Additional context**
Without poking around the code, it looks like the page is doing some work in `componentDidMount` that isn't being correctly handled in `componentDidUpdate`. Or a `useEffect` is missing some dependencies.

Edit: Screenshot

### PR DESCRIPTION
**Pull request by airjp73**
Fixes #1066 

## Gif with fix
_Note_: The link in the gif is something I stubbed in locally
Mar-22-2020 16-05-22

## Proposed Changes
I was right about my hunch. There are side-effects in a couple components that are being handled on mount, but not when important props change.

### CODE REVIEW

File: src/components/Chat/Chat.tsx [hunk 1]
```diff
@@ -902,7 +902,7 @@ export class Chat extends React.Component<ChatProperties, ChatState> {
 
 export class EmbeddedChat extends React.PureComponent<ChatProperties, {}> {
     render() {
-        return <Card className="Card EmbeddedChat"><Chat {...this.props} /></Card>;
+        return <Card className="Card EmbeddedChat"><Chat key={this.props.channel} {...this.props} /></Card>;
```
Comment (airjp73) [inline src/components/Chat/Chat.tsx]: The `Chat` component has more complicated side-effects than the table. I figured if we just reload the entire component when the channel changes, that was the approach with the least risk of breaking things. I'm happy to take a stab at fixing it properly in the `Chat` component itself if you want, though.

**Comment by anoek** [comment]
Awesome, thanks for the fix!

**Comment by airjp73** [comment]
Happy to help! 😊
